### ISSUE TITLE
Export Data as CSV

### ISSUE THREAD

**Issue by wellcaffeinated** [spdcalc/spdcalc#5]
feature request

**Comment by kshalm** [comment]
The CSV file is missing the x axis and y-axis labels. It is basically impossible to use the data to make a plot without it. I'd suggest either write out a file with the following format. Perhaps a JSON encoding would be helpful for the export with the following data.

```
Plot type: Description of plot  
X-axis range: 1550, 1560, ....
Y-axis range: 1200, 1210, ....
Units (x,y,z): (nm,nm, abu)
Data: CSV 2D
```

For now, even just adding the x/y data would be helpful
```
x1,x2,x3, ...  # X axis values
y1,y2, y3, ...  # Y axis values
Data
```

**Comment by wellcaffeinated** [comment]
Added the formatting:
```
xvals: 1, 2, 3
yvals: 1, 2, 3
.1, .2, .3
.4, .5, .6
...
```
